# pull official base image
FROM node:14 AS builder

# set working directory
WORKDIR /app


# install app dependencies
#copies package.json and package-lock.json to Docker environment
COPY ./src/client/package.json ./

# Installs all node packages
RUN npm install 


# Copies everything over to Docker environment
COPY ./src/client ./
RUN npm run build

#Stage 2
#######################################
FROM nginx:1.21.0
#copies React to the container directory
# Set working directory to nginx resources directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static resources
RUN rm -rf ./*
# Copies static resources from builder stage
COPY --from=builder /app/build .
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]