FROM node:14 AS builder
WORKDIR /usr/src/app
COPY src/server/src src
COPY src/server/package*.json ./
COPY src/server/tsconfig*.json ./
RUN npm install -g typescript
RUN yarn
RUN yarn run build

FROM node:14
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY src/server/package*.json ./
COPY src/server/db db
RUN yarn install --production
COPY --from=builder /usr/src/app/dist/ dist/
RUN mkdir /usr/src/app/dist/uploads
EXPOSE 5050
ENTRYPOINT [ "node", "dist/index.js" ]